### ISSUE TITLE
Need to add missing dependencies

### ISSUE THREAD

**Issue by rbarman** [jgoman99/SEC-Parsers#2]
Installed library in a fresh virtual environment

```sh
python -m venv venv
.\venv\Scripts\activate
# sec-parsers in requirements.txt
pip install -r .\requirements.txt
```

Tried sample code from README but it fails

```python
from sec_parsers import Filing, download_sec_filing
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "my_folders\venv\Lib\site-packages\sec_parsers\__init__.py", line 2, in <module>
    from .download import download_sec_filing, set_headers
  File "my_folder\venv\Lib\site-packages\sec_parsers\download.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

We probably need to update setup.py (https://github.com/john-friedman/SEC-Parsers/blob/main/sec_parsers/setup.py#L14) with `requests` and any other required dependencies.

**Comment by john-friedman** [comment]
Thanks! Should be fixed now.

**Comment by rbarman** [comment]
Thank you. I reinstalled and it works now
